### ISSUE TITLE
Player currently start with too good equipments.

### ISSUE THREAD

**Issue by e666666** [CuAnnan/Downlink#57]
Player might just start with worse cpu, less secure connection since it is currently unbreakable, and also start with "smaller" tasks, perhap start with hacking with only dictionary attack required?
And then, make stuff cheaper.

**Comment by Downlink-idle** [comment]
Balance is something that will see ongoing tweaking, at present only passwords are scaling properly and the encryption grid is not.

But at present, the game requires more structural and logistic testing than fine tuning. And to facilitate that, progress walls cannot be a thing.

The discord link has been updated and will roll out in a few minutes.
